apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w546y1mge-dotnet-basic
  janus-idp.io/tekton: w546y1mge-dotnet-basic
  backstage.io/kubernetes-id: w546y1mge-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w546y1mge-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
